title:
logo: /assets/img/profile_pic.jpg
description: <h1>Bithin Alangot</h1><br /> Visiting Fellow at Singapore University of Technology and Design, PhD Student at Amrita Vishwa Vidyapeetham
#show_downloads: true
google_analytics:
#theme: jekyll-theme-minimal
#theme: minima
remote_theme: luizdepra/hugo-coder
