title: Bithin Alangot
logo: /assets/img/profile_pic.jpg
description: Visiting Fellow at Singapore University of Technology and Design
#show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
